version: '3.1'

# Default ${TEAMCITY_VERSION} is defined in .env file

# ./buildserver_pgdata - Posgres DB data
# ./data_dir - TeamCity data directory
# ./teamcity-server-logs - logs of primary TeamCity server
# ./agents/agent-1/conf - configuration directory for the first build agent
# ./agents/agent-1/conf - configuration directory for the second build agent
volumes:
  buildserver_pgdata:
  gogs-data:
services:
  db:
    profiles:
      - tc
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=teamcity_password
      - POSTGRES_USER=teamcity_user
      - POSTGRES_DB=teamcity_db
      - PG_DATA=/var/lib/postgresql/data
    volumes:
      - buildserver_pgdata:/var/lib/postgresql/data
    ports:
      - 5433:5432

  teamcity:
    image: jetbrains/teamcity-server:${TEAMCITY_VERSION}-linux
    profiles:
      - tc
    user: root
    ports:
      - "8112:8111"
    volumes:
      - ./data_dir:/data/teamcity_server/datadir
      - ./teamcity-server-logs:/opt/teamcity/logs
    depends_on:
      - db
      - gogs

  teamcity-agent-1:
    image: jetbrains/teamcity-agent:${TEAMCITY_VERSION}-linux-sudo
    profiles:
      - tc
    privileged: true
    volumes:
      - ./agent/conf:/data/teamcity_agent/conf
    environment:
      - DOCKER_IN_DOCKER=start
    depends_on:
      - gogs

  vault-server:
    image: vault:1.13.3
    profiles:
      - tc
      - jenkins
      - vault
    ports:
      - "8200:8200"
    environment:
      - "VAULT_ADDR=http://0.0.0.0:8200"
      - "VAULT_DEV_ROOT_TOKEN_ID=root"
    cap_add:
      - IPC_LOCK
    healthcheck:
      test: [ "CMD", "vault", "status" ]
      interval: 5s
      timeout: 3s
      retries: 100
      start_period: 5s

  vault-client:
    build: ./vault-client
    profiles:
      - tc
      - jenkins
      - vault
    environment:
      VAULT_ADDR: "http://vault-server:8200"
    depends_on:
      vault-server:
        condition: service_healthy
    volumes:
      - ./vault-client/init.sh:/init.sh
      - ./vault-client/secrets.json:/secrets.json

  jenkins:
    image: jenkins/jenkins:latest-jdk21-preview
    profiles:
      - jenkins
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ./jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  gogs:
    image: gogs/gogs:latest
    profiles:
      - jenkins
      - tc
    ports:
      - "2222:2222"
      - "3001:3001"
    volumes:
      - "gogs-data:/data"
      - "./gogs.ini:/data/gogs/conf/app.ini"

